#ifndef GAME_PLAY_H
#define GAME_PLAY_H

typedef enum
{
    PLAYER_CONTROL_NONE,
    PLAYER_CONTROL_MOVE_UP,
    PLAYER_CONTROL_MOVE_DOWN,
    PLAYER_CONTROL_MOVE_LEFT,
    PLAYER_CONTROL_MOVE_RIGHT,
    PLAYER_CONTROL_BOMB,
    PLAYER_CONTROL_TRAP,
    PLAYER_CONTROL_COUNT
}
PlayerControlType;

#endif
